apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-api
  template:
    metadata:
      labels:
        app: expense-api
    spec:
      containers:
        - name: api
          image: yourregistry/expense-api:latest
          env:
            - name: POSTGRES_URL
              value: "postgres://postgres:password@postgres-svc:5432/expenses?sslmode=disable"
            - name: REDIS_ADDR
              value: "redis:6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: secret
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: expense-api-svc
spec:
  selector:
    app: expense-api
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
